#!/usr/bin/env bash
set -euo pipefail

src_dir=src
asset_dir=asset
dist_dir=dist
phaser_file=node_modules/phaser/build/phaser.min.js

mkdir -p "$dist_dir"
cp -af "$src_dir/index-prod.htm" "$dist_dir/index.htm"
cp -af \
  "$phaser_file" \
  "$asset_dir" \
  "$dist_dir"
jspm build --minify "$src_dir/index" "$dist_dir/index.js"